#!/bin/bash

# Check if PHPCS is installed.
which ./vendor/bin/phpcs &> /dev/null
if [[ "$?" == 1 ]]; then
  echo -e "\nPHPCS not detected in vendor/bin. Please install PHPCS.\n"
  exit 1
fi

# Gather staged files added to commit.
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

# Check if files are present.
if [[ "$STAGED_FILES" = "" ]]; then
    echo -e "\nNo staged files.\n"
    exit 0
fi

echo -e "\nPHPCS validation started.\n"

PASS_CHECK=true

# Run PHPCS on staged files and set passed/failed state.
for FILE in ${STAGED_FILES}
    do
        ./vendor/bin/phpcs $FILE &> /dev/null

        if [[ "$?" == 0 ]]; then
            echo -e "\e[92m\e[1mPassed:\e[0m $FILE"
        else
            echo -e "\e[91m\e[1mFailed:\e[0m $FILE"
            PASS_CHECK=false
        fi
    done

echo -e "\nPHPCS validation finished.\n"

# Check if errors are present and exit/continue commit.
if ! ${PASS_CHECK}; then
    echo -e "\e[91m\e[1mCOMMIT FAILED:\e[0m Commit contains files that failed PHPCS validation.\n"
    exit 1
else
    echo -e "\e[92m\e[1mCOMMIT SUCCEEDED.\e[0m\n"
fi

exit $?
